project:
  type: default
  title: "Python Sandbox"
  # (Optional) Limit default renders to certain folders:
  # render:
  #   - notebooks/**/*.ipynb
  #   - docs/**/*.qmd

execute:
  echo: false
  warning: false
  error: false
  cache: false       # set true for faster rebuilds while iterating
  freeze: auto       # only re-render when source changes
  dpi: 150
  fig-width: 7
  fig-height: 4
  fig-align: center

format:
  html:
    theme: [cosmo, darkly]     # light/dark auto
    css: styles.css            # ensures Fira Code in HTML code blocks
    toc: true
    toc-location: left
    code-fold: show
    code-tools: true
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true
    highlight-style: github
  pdf:
    pdf-engine: lualatex        # needed for fontspec/unicode-math
    include-in-header: _preamble.tex
    toc: true
    number-sections: false
    geometry:
      - margin=1in
    keep-tex: false             # set true if debugging PDF builds
  docx:
    toc: true
  revealjs:
    theme: serif
    slide-number: true
    progress: true
    code-overflow: wrap
    chalkboard: false
