project:
  type: default
  title: "Python Sandbox"
  output-dir: build
  render:
    - notebooks/**/*.qmd
    - notebooks/**/*.ipynb

execute:
  echo: true            # (for .ipynb) normal code+output
  warning: false
  error: false
  cache: false
  freeze: auto
  dpi: 300
  fig-width: 7
  fig-height: 4
  fig-align: center

format:
  html:
    theme: [cosmo, darkly]
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: show
    code-tools: true
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true
    highlight-style: github

  pdf:
    pdf-engine: lualatex
    include-in-header:
      - _preamble.tex
    listings: true            # make Pandoc use LaTeX listings
    code-block-class: codeblock  # wrap each code block in our tcolorbox
    toc: true
    toc-depth: 3
    number-sections: true
    geometry:
      - margin=1in
    keep-tex: false

  docx:
    toc: true

  revealjs:
    theme: serif
    slide-number: true
    progress: true
    code-overflow: wrap
    chalkboard: false
