[project]
name = "python-sandbox"
version = "0.1.0"
description = "Public mono-repo for notebooks (tutoring), reusable Python modules, tests, and docs."
requires-python = ">=3.10"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
fix = true
unsafe-fixes = true

[tool.ruff.lint]
select = ["E","F","I","UP","B","SIM","W","C90","N","ANN"]

[tool.ruff.format]
quote-style = "double"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-q --testmon"
testpaths = ["tests"]

[tool.mypy]
python_version = "3.10"
strict = false
ignore_missing_imports = true
