line-length = 100
src = ["src", "tests"]
target-version = "py310"
fix = true
unsafe-fixes = true

[lint]
select = ["E", "F", "I", "UP", "B", "SIM", "W", "C90", "N", "ANN"]

[lint.isort]
lines-after-imports = 2
order-by-type = true

[format]
quote-style = "double"
