[project]
name = "insight-app"
version = "0.1.0"
description = "Insight application placeholder"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=7.0", "ruff>=0.5"]
