project:
  type: default
  output-dir: build

execute:
  echo: false
  warning: false
  error: false
  cache: false
  freeze: auto

format:
  html:
    toc: true
    code-fold: show
    code-tools: true
  pdf:
    pdf-engine: tectonic
    toc: true
    geometry: "margin=1in"
  docx:
    toc: true
  revealjs:
    theme: default   # try: simple, serif, solarized
    slide-number: true
    controls: true
    progress: true
    code-overflow: wrap
    code-line-numbers: false
    chalkboard: false
