[project]
name = "panel-apps"
version = "0.1.0"
description = "Panel demos for the sandbox project"
requires-python = ">=3.10"
dependencies = [
    "panel>=1.2",
    "hvplot>=0.9",
    "pandas>=1.5",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "ruff>=0.5",
]
