name: deep-review

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  deep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Skip if no changes in last 2 hours
        id: delta
        run: |
          if [ -z "$(git log --all --since='2 hours ago' --oneline)" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Stop early
        if: steps.delta.outputs.changed == 'false'
        run: echo "No changes in last 2 hours. Exiting."

      - uses: actions/setup-python@v5
        if: steps.delta.outputs.changed == 'true'
        with: { python-version: '3.10' }

      - name: Install deps
        if: steps.delta.outputs.changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy pytest
          pip install -e .

      - name: Lint & Type & Tests
        id: check
        if: steps.delta.outputs.changed == 'true'
        continue-on-error: true
        run: |
          ruff check . && black --check . && mypy . && pytest -q

      - name: Create or update deep-review issue on failure
        if: steps.delta.outputs.changed == 'true' && steps.check.outcome != 'success'
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const title = "Deep review failures";
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner, repo, state: "open", labels: "deep-review"
            });
            const body = `Automated deep review found issues in lint/type/tests at ${new Date().toISOString()}.\n\nRun ID: ${context.runId}`;
            if (issues.length > 0) {
              await github.rest.issues.createComment({ owner, repo, issue_number: issues[0].number, body });
            } else {
              await github.rest.issues.create({ owner, repo, title, body, labels: ['bug','automated','deep-review'] });
            }
